(require-package 'cmake-ide)
(require 'rtags) ;; optional, must have rtags installed
(cmake-ide-setup)

(define-major 'c++-mode
  ("m." 'rtags-find-symbol-at-point)
  ("m," 'rtags-find-references-at-point)
  ("mv" 'rtags-find-virtuals-at-point)
  ("mV" 'rtags-print-enum-value-at-point)
  ("m/" 'rtags-find-all-references-at-point)
  ("my" 'rtags-cycle-overlays-on-screen)
  ("m>" 'rtags-find-symbol)
  ("m<" 'rtags-find-references)
  ("m[" 'rtags-location-stack-back)
  ("m]" 'rtags-location-stack-forward)
  ("md" 'rtags-diagnostics)
  ("mg" 'rtags-guess-function-at-point)
  ("mp" 'rtags-set-current-project)
  ("mP" 'rtags-print-dependencies)
  ("me" 'rtags-reparse-file)
  ("mE" 'rtags-preprocess-file)
  ("mr" 'rtags-rename-symbol)
  ("mm" 'rtags-symbol-info)
  ("ms" 'rtags-display-summary)
  ("mo" 'rtags-goto-offset)
  ("m;" 'rtags-find-file)
  ("mf" 'rtags-fixit)
  ("ml" 'rtags-copy-and-print-current-location)
  ("mx" 'rtags-fix-fixit-at-point)
  ("mb" 'rtags-show-rtags-buffer)
  ("mi" 'rtags-imenu)
  ("mt" 'rtags-taglist)
  ("mh" 'rtags-print-class-hierarchy)
  ("ma" 'rtags-print-source-arguments))
